version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
#    image: maven:3.8.1-jdk-11
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "5006:5005"
      - "8090:8080"
    volumes:
      - ./:/home/
      - mvn_dependencies:/root/.m2
    command: /bin/sh -c "cd /home/ && ./mvnw dependency:go-offline -Dmaven.test.skip jetty:run"
    depends_on:
      - hapi-fhir-postgresql
    networks:
      network:
        aliases:
          - jpaserver
  hapi-fhir-postgresql:
    image: postgres:11
    container_name: hapi-fhir-postgresql
    ports:
      - "5452:5432"
    environment:
      - POSTGRES_DB=hapi_dstu3
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-hapi:/var/lib/postgresql/data
    networks:
      network:
        aliases:
          - hapi-fhir-postgresql
    restart: always
volumes:
  mvn_dependencies:
    external: true
  postgres-hapi:
    external: true
networks:
  network: